[supervisord]
nodaemon=true

[program:chroma]
command=chroma run --path /app/db --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nest]
command=pnpm run start:prod
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
